### PR TITLE
To-Do List:  Add & Remove

### PR DESCRIPTION
**Pull request by rotimiazeez**
# To-Do List:  Add & Remove🎉 

> This PR describes implementing the CRUD (create, update, delete) methods. All the elements of the user interface will be fully functional and your application will be completed. 💪🏽 

Additional description of the project and its features. ➕ 🚀  

- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for editing task descriptions.
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for the "Clear all completed" button (use filter() method).
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To-Do List should be saved in local storage.

## Built With ❤️ 

- HTML (HTML5 semantic tags, `ul`, `li`,  `button`)
- CSS
-  Javascript (DOM manipulation, ES6 and Webpack)

## Deployed Preview 🚀 
[Live Preview](https://deploy-preview-3--rotimiazeez-to-do-list-app.netlify.app)

### NOTE TO REVIEWER 😉 ❤️  
 😃 👍🏽

### CODE REVIEW

**Review by mimipeshy — CHANGES_REQUESTED** [review]
## Hi @rotimiazeez  👋🏾 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
#### Highlights

- I can create, update and delete todo's ✔️ 
- good GitHub workflow ✔️ 
- not forming any linter errors ✔️ 

## Required Changes ♻️

- [x] Since this is the last step of the to-do's let's make sure everything is ready. This means updating the live demo link in your README file with the live link, it's already in your PR 😄 . Then after a user has installed the packages using `npm i` they need to start the server using `npm start` kindly add the last part in your README.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Comment by rotimiazeez** [comment]
Hi @mimipeshy 👋🏽,
Good to have you on my PR again👍🏽. I have made the required changes and hope to be approved now 💯 .

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @rotimiazeez  🔥 

You worked hard in all the instructions that the previous Code Reviewer gives you👍🏽 

goodjob

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rotimiazeez** [comment]
Hi @mricanho 👋🏽, 
Thanks for approving the project 👏🏽, that will be all for now 💯

**Pull request merged**
